apiVersion: apps/v1
kind: Deployment
metadata:
  name: workpace-app
  namespace: workpace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workpace-app
  template:
    metadata:
      labels:
        app: workpace-app
    spec:
      containers:
        - name: workpace-app
          image: ${DOCKER_REGISTRY}/workpace-app:${VERSION}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: workpace-secrets
                  key: database-url
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: workpace-secrets
                  key: nextauth-secret
            - name: NEXTAUTH_URL
              value: "https://workpace.io"
          # Add other environment variables as needed
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
