export enum Routes {
  HOME = '/',
  APPS = '/apps',
  GOOD_STUFF_LIST = 'apps/good-stuff-list',
  SMS = 'apps/sms',
  SIGNIN = '/signin',
  ABOUT = '/about',
  PROFILE = '/profile',
  FRIENDS = '/friends',
  TEMPLATES = '/templates',
  ADMIN = '/admin',
  ADMIN_FEATURES = '/admin/features',
  ADMIN_SMS = '/admin/sms',
  PRIVACY = '/privacy',
  TERMS = '/terms',
}
