export enum Routes {
  HOME = '/',
  APPS = '/apps',
  GOOD_STUFF_LIST = 'apps/good-stuff-list',
  SMS = 'apps/sms',
  SIGNIN = '/signin',
  ABOUT = '/about',
  PROFILE = '/profile',
  FRIENDS = '/friends',
  TEMPLATES = '/templates',
  ADMIN = '/admin',
  ADMIN_FEATURES = '/admin/features',
  ADMIN_SMS = '/admin/sms',
  PORTAL = '/portal',
  PORTAL_INTAKE = '/portal/intake',
  PORTAL_CONTRACTS = '/portal/contracts',
  PORTAL_STATUS = '/portal/status',
  PORTAL_REQUESTS = '/portal/requests',
  PORTAL_SETTINGS = '/portal/settings',
  PORTAL_SIGNUP = '/portal/signup',
  ADMIN_PORTAL = '/admin/portal',
  ADMIN_INTAKES = '/admin/intakes',
  ADMIN_PIPELINE = '/admin/pipeline',
  PRIVACY = '/privacy',
  TERMS = '/terms',
}
