name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: registry.digitalocean.com/workpace
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Digital Ocean Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/workpace-app:${{ github.sha }}
            ${{ env.DOCKER_REGISTRY }}/workpace-app:latest

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Update Kubernetes deployment
        run: |
          # Apply namespace if it doesn't exist
          kubectl apply -f k8s/namespace.yaml

          # Update image version in deployment.yaml
          sed -i "s|\${DOCKER_REGISTRY}|$DOCKER_REGISTRY|g" k8s/deployment.yaml
          sed -i "s|\${VERSION}|${{ github.sha }}|g" k8s/deployment.yaml

          # Apply Kubernetes configurations
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml

          # Verify deployment
          kubectl rollout status deployment/workpace-app -n workpace
